/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t BGT_sample_ase[];
extern const uint8_t BGT_sample_ase_end[];
#if __cplusplus >= 201103L
static constexpr size_t BGT_sample_ase_size=3104;
#else
static const size_t BGT_sample_ase_size=3104;
#endif
extern const uint8_t BGT_sample_bmp[];
extern const uint8_t BGT_sample_bmp_end[];
#if __cplusplus >= 201103L
static constexpr size_t BGT_sample_bmp_size=3072;
#else
static const size_t BGT_sample_bmp_size=3072;
#endif
extern const uint8_t BG_sample_ase[];
extern const uint8_t BG_sample_ase_end[];
#if __cplusplus >= 201103L
static constexpr size_t BG_sample_ase_size=2048;
#else
static const size_t BG_sample_ase_size=2048;
#endif
extern const uint8_t BG_sample_bmp[];
extern const uint8_t BG_sample_bmp_end[];
#if __cplusplus >= 201103L
static constexpr size_t BG_sample_bmp_size=2048;
#else
static const size_t BG_sample_bmp_size=2048;
#endif
extern const uint8_t PAL_test[];
extern const uint8_t PAL_test_end[];
#if __cplusplus >= 201103L
static constexpr size_t PAL_test_size=32;
#else
static const size_t PAL_test_size=32;
#endif
extern const uint8_t PAL_test2[];
extern const uint8_t PAL_test2_end[];
#if __cplusplus >= 201103L
static constexpr size_t PAL_test2_size=32;
#else
static const size_t PAL_test2_size=32;
#endif
extern const uint8_t sprites_c[];
extern const uint8_t sprites_c_end[];
#if __cplusplus >= 201103L
static constexpr size_t sprites_c_size=36168;
#else
static const size_t sprites_c_size=36168;
#endif
extern const uint8_t sprites_h[];
extern const uint8_t sprites_h_end[];
#if __cplusplus >= 201103L
static constexpr size_t sprites_h_size=479;
#else
static const size_t sprites_h_size=479;
#endif
extern const uint8_t SPR_test[];
extern const uint8_t SPR_test_end[];
#if __cplusplus >= 201103L
static constexpr size_t SPR_test_size=128;
#else
static const size_t SPR_test_size=128;
#endif
